# Travis-CI build script for sdsl-lite

language: cpp

cache:
  apt: true
  ccache: true

sudo: false

matrix:
  include:
    - env: MYCC="gcc-4.9" MYCXX="g++-4.9" STDLIB=libstdc++ MYBUILD=Debug
      os: linux
      addons: &gcc49
        apt:
          sources:
            - kalakris-cmake
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-4.9

    - env: MYCC="gcc-4.9" MYCXX="g++-4.9" STDLIB=libstdc++ MYBUILD=Release
      os: linux
      addons: &gcc49
        apt:
          sources:
            - kalakris-cmake
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-4.9

    - env: MYCC="gcc-5" MYCXX="g++-5" STDLIB=libstdc++ MYBUILD=Debug
      os: linux
      addons: &gcc5
        apt:
          sources:
            - kalakris-cmake
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-5

    - env: MYCC="gcc-5" MYCXX="g++-5" STDLIB=libstdc++ MYBUILD=Release
      os: linux
      addons: &gcc5
        apt:
          sources:
            - kalakris-cmake
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-5

    - env: MYCC="gcc-6" MYCXX="g++-6" STDLIB=libstdc++ MYBUILD=Debug
      os: linux
      addons: &gcc6
        apt:
          sources:
            - kalakris-cmake
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-6

    - env: MYCC="gcc-6" MYCXX="g++-6" STDLIB=libstdc++ MYBUILD=Release
      os: linux
      addons: &gcc6
        apt:
          sources:
            - kalakris-cmake
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-6

before_script:
  - export CXX=$MYCXX
  - export CC=$MYCC
  - $CXX --version
  - cmake --version
  - ccache --version

script:
  - cd ${TRAVIS_BUILD_DIR}
#  - ./install.sh ..
  - mkdir sdsl-lite-build && cd sdsl-lite-build
  - cmake ${TRAVIS_BUILD_DIR} -DCMAKE_BUILD_TYPE=$MYBUILD
  - make -k -j 2
  - ctest -j 2
#--output-on-failure

after_script:
  - ccache -s
